# Neutron Collector
mods.avaritia.ExtremeCrafting.remove(<avaritia:neutron_collector>);
mods.avaritia.ExtremeCrafting.addShaped("Neutron Collector", <avaritia:neutron_collector> * 2, [[<contenttweaker:tungsten_ingot>, <thermalfoundation:storage:7>, <contenttweaker:tungsten_ingot>, <avaritia:resource:1>, <contenttweaker:tungsten_ingot>, <avaritia:resource:1>, <contenttweaker:tungsten_ingot>, <thermalfoundation:storage:7>, <contenttweaker:tungsten_ingot>], [<thermalfoundation:storage:7>, <enderio:block_infinity:0>, <enderio:block_infinity:0>, null, null, null, <enderio:block_infinity:0>, <enderio:block_infinity:0>, <thermalfoundation:storage:7>],[<contenttweaker:tungsten_ingot>, <enderio:block_infinity:0>, null, <draconicevolution:draconium_block:1>, <draconicevolution:draconium_block:1>, <draconicevolution:draconium_block:1>, null, <enderio:block_infinity:0>, <contenttweaker:tungsten_ingot>],[<avaritia:resource:1>, null, <draconicevolution:draconium_block:1>, <draconicevolution:draconium_block:1>, <draconicevolution:draconium_block:1>, <draconicevolution:draconium_block:1>, <draconicevolution:draconium_block:1>, null, <avaritia:resource:1>],[<contenttweaker:tungsten_ingot>, null, <draconicevolution:draconium_block:1>, <draconicevolution:draconium_block:1>, <contenttweaker:densium_ingot>, <draconicevolution:draconium_block:1>, <draconicevolution:draconium_block:1>, null, <contenttweaker:tungsten_ingot>],[<avaritia:resource:1>, null, <draconicevolution:draconium_block:1>, <draconicevolution:draconium_block:1>, <draconicevolution:draconium_block:1>, <draconicevolution:draconium_block:1>, <draconicevolution:draconium_block:1>, null, <avaritia:resource:1>],[<contenttweaker:tungsten_ingot>, <enderio:block_infinity:0>, null, <draconicevolution:draconium_block:1>, <draconicevolution:draconium_block:1>, <draconicevolution:draconium_block:1>, null, <enderio:block_infinity:0>, <contenttweaker:tungsten_ingot>],[<thermalfoundation:storage:7>, <enderio:block_infinity:0>, <enderio:block_infinity:0>, null, null, null, <enderio:block_infinity:0>, <enderio:block_infinity:0>, <thermalfoundation:storage:7>],[<contenttweaker:tungsten_ingot>, <thermalfoundation:storage:7>, <contenttweaker:tungsten_ingot>, <avaritia:resource:1>, <contenttweaker:tungsten_ingot>, <avaritia:resource:1>, <contenttweaker:tungsten_ingot>, <thermalfoundation:storage:7>, <contenttweaker:tungsten_ingot>]]);

# Neutron Compressor
mods.avaritia.ExtremeCrafting.remove(<avaritia:neutronium_compressor>);
mods.avaritia.ExtremeCrafting.addShaped("Neutronium Compressor", <avaritia:neutronium_compressor> * 1, [[<contenttweaker:tungsten_ingot>, <thermalfoundation:storage:7>, <contenttweaker:tungsten_ingot>, <avaritia:block_resource:2>, <contenttweaker:tungsten_ingot>, <avaritia:block_resource:2>, <contenttweaker:tungsten_ingot>, <thermalfoundation:storage:7>, <contenttweaker:tungsten_ingot>], [<avaritia:block_resource:2>, null, <avaritia:resource:4>, null, null, null, <avaritia:resource:4>, null, <avaritia:block_resource:2>],[<thermalfoundation:storage:7>, <redstonearsenal:material:96>, <avaritia:resource:4>, null, null, null, <avaritia:resource:4>, <redstonearsenal:material:96>, <thermalfoundation:storage:7>],[<avaritia:block_resource:2>, <draconicevolution:draconic_energy_core>, <avaritia:resource:4>, null, null, null, <avaritia:resource:4>, <draconicevolution:draconic_energy_core>, <avaritia:block_resource:2>],[<contenttweaker:tungsten_ingot>, <avaritia:block_resource:0>, <avaritia:resource:4>, null, <contenttweaker:block_densium:0>, null, <avaritia:resource:4>, <avaritia:block_resource:0>, <contenttweaker:tungsten_ingot>],[<avaritia:block_resource:2>, <draconicevolution:draconic_energy_core>, <avaritia:resource:4>, null, null, null, <avaritia:resource:4>, <draconicevolution:draconic_energy_core>, <avaritia:block_resource:2>],[<thermalfoundation:storage:7>, <redstonearsenal:material:96>, <avaritia:resource:4>, null, null, null, <avaritia:resource:4>, <redstonearsenal:material:96>, <thermalfoundation:storage:7>],[<avaritia:block_resource:2>, null, <avaritia:resource:4>, null, null, null, <avaritia:resource:4>, null, <avaritia:block_resource:2>],[<contenttweaker:tungsten_ingot>, <thermalfoundation:storage:7>, <contenttweaker:tungsten_ingot>, <avaritia:block_resource:2>, <contenttweaker:tungsten_ingot>, <avaritia:block_resource:2>, <contenttweaker:tungsten_ingot>, <thermalfoundation:storage:7>, <contenttweaker:tungsten_ingot>]]);

# Remove Extreme Recipes
mods.avaritia.ExtremeCrafting.remove(<eternalsingularity:eternal_singularity>);
mods.avaritia.ExtremeCrafting.remove(<avaritia:resource:5>);
mods.avaritia.ExtremeCrafting.remove(<avaritia:resource:6>);
recipes.remove(<singularities:compressor>);
mods.jei.JEI.hide(<singularities:compressor>);
mods.jei.JEI.hideCategory("singularities.compressor");

# Neutronium系
recipes.remove(<avaritia:resource:2>);
recipes.remove(<avaritia:resource:3>);
recipes.remove(<avaritia:resource:4>);
recipes.remove(<avaritia:block_resource>);
mods.thermalexpansion.Compactor.addStorageRecipe(<avaritia:resource:3>, <avaritia:resource:2>*10, 10000);
mods.thermalexpansion.Compactor.addStorageRecipe(<avaritia:resource:4>, <avaritia:resource:3>*10, 40000);
mods.thermalexpansion.Compactor.addStorageRecipe(<avaritia:block_resource>, <avaritia:resource:4>*16, 160000);

mods.thermalexpansion.Factorizer.removeRecipeSplit(<avaritia:block_resource>);
mods.thermalexpansion.Factorizer.removeRecipeSplit(<avaritia:resource:4>);
mods.thermalexpansion.Factorizer.removeRecipeSplit(<avaritia:resource:3>);
mods.thermalexpansion.Factorizer.removeRecipeCombine(<avaritia:resource:2> * 9);
mods.thermalexpansion.Factorizer.removeRecipeCombine(<avaritia:resource:3> * 9);
mods.thermalexpansion.Factorizer.removeRecipeCombine(<avaritia:resource:4> * 9);

// Ultimate Stew
mods.avaritia.ExtremeCrafting.remove(<avaritia:ultimate_stew>);
mods.avaritia.ExtremeCrafting.addShaped("Stew", <avaritia:ultimate_stew> * 32, [[null, <harvestcraft:currypowderitem>, <harvestcraft:currypowderitem>, <avaritia:resource:4>, <harvestcraft:netherstartoastitem>, <avaritia:resource:4>, <harvestcraft:currypowderitem>, <harvestcraft:currypowderitem>, null], [<contenttweaker:tungsten_ingot>, <actuallyadditions:item_jam:5>, <harvestcraft:deluxechickencurryitem>, <harvestcraft:deluxechickencurryitem>, <avaritia:resource:4>, <harvestcraft:deluxechickencurryitem>, <harvestcraft:deluxechickencurryitem>, <actuallyadditions:item_jam:6>, <contenttweaker:tungsten_ingot>],[null, <contenttweaker:tungsten_ingot>, <actuallyadditions:item_jam:0>, <actuallyadditions:item_jam:1>, <actuallyadditions:item_jam:2>, <actuallyadditions:item_jam:3>, <actuallyadditions:item_jam:4>, <contenttweaker:tungsten_ingot>, null],[<contenttweaker:tungsten_ingot>, <harvestcraft:cashewitem>, <harvestcraft:applejuiceitem>, <harvestcraft:melonjuiceitem>, <harvestcraft:carrotjuiceitem>, <harvestcraft:strawberryjuiceitem>, <harvestcraft:grapejuiceitem>, <harvestcraft:figitem>, <contenttweaker:tungsten_ingot>],[<contenttweaker:tungsten_ingot>, <harvestcraft:cherryitem>, <harvestcraft:bananaitem>, <nuclearcraft:moresmore>, <harvestcraft:durianitem>, <nuclearcraft:moresmore>, <harvestcraft:breadfruititem>, <harvestcraft:papayaitem>, <contenttweaker:tungsten_ingot>],[<contenttweaker:tungsten_ingot>, <harvestcraft:plumitem>, <harvestcraft:jackfruititem>, <harvestcraft:grapefruititem>, <harvestcraft:dragonfruititem>, <harvestcraft:pomegranateitem>, <harvestcraft:avocadoitem>, <harvestcraft:mangoitem>, <contenttweaker:tungsten_ingot>],[<contenttweaker:tungsten_ingot>, <harvestcraft:cranberryitem>, <harvestcraft:peachitem>, <harvestcraft:huckleberryitem>, <harvestcraft:persimmonitem>, <harvestcraft:juniperberryitem>, <harvestcraft:orangeitem>, <harvestcraft:raspberryitem>, <contenttweaker:tungsten_ingot>],[<thermalfoundation:material:1024>, <contenttweaker:tungsten_ingot>, <harvestcraft:elderberryitem>, <harvestcraft:mulberryitem>, <harvestcraft:gooseberryitem>, <harvestcraft:blueberryitem>, <harvestcraft:blackberryitem>, <contenttweaker:tungsten_ingot>, <thermalfoundation:material:1024>],[<enderio:item_alloy_ball:6>, <thermalfoundation:material:1024>, <contenttweaker:tungsten_ingot>, <contenttweaker:tungsten_ingot>, <contenttweaker:tungsten_ingot>, <contenttweaker:tungsten_ingot>, <contenttweaker:tungsten_ingot>, <thermalfoundation:material:1024>, <enderio:item_alloy_ball:6>]]);

// Sword of the Cosmos
mods.avaritia.ExtremeCrafting.remove(<avaritia:infinity_sword>);
mods.avaritia.ExtremeCrafting.addShaped("Cosmos", <avaritia:infinity_sword> * 1, [[null, null, null, null, null, null, null, <avaritia:resource:6>, <avaritia:resource:6>], [null, null, null, null, null, null, <avaritia:resource:6>, <contenttweaker:block_chaos_tungsten:0>, <avaritia:resource:6>],[null, null, null, null, null, <avaritia:resource:6>, <contenttweaker:block_chaos_tungsten:0>, <avaritia:resource:6>, null],[null, null, null, null, <avaritia:resource:6>, <contenttweaker:block_chaos_tungsten:0>, <avaritia:resource:6>, null, null],[null, <avaritia:block_resource:2>, null, <avaritia:resource:6>, <contenttweaker:block_chaos_tungsten:0>, <avaritia:resource:6>, null, null, null],[null, null, <avaritia:block_resource:2>, <contenttweaker:block_chaos_tungsten:0>, <avaritia:resource:6>, null, null, null, null],[null, null, <contenttweaker:block_chaos_tungsten>, <avaritia:block_resource:2>, null, null, null, null, null],[null, <contenttweaker:block_chaos_tungsten:0>, null, null, <avaritia:block_resource:2>, null, null, null, null],[<avaritia:resource:5>, null, null, null, null, null, null, null, null]]);

// Longbow of the Heavens
mods.avaritia.ExtremeCrafting.remove(<avaritia:infinity_bow>);
mods.avaritia.ExtremeCrafting.addShaped("Heavens", <avaritia:infinity_bow> * 1, [[null, null, null, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, null, null, null], [null, null, <avaritia:resource:6>, <contenttweaker:block_chaos_tungsten:0>, <extrabotany:material:7>, null, null, null, null],[null, <avaritia:resource:6>, <contenttweaker:block_chaos_tungsten:0>, null, <extrabotany:material:7>, null, null, null, null],[<avaritia:resource:6>, <contenttweaker:block_chaos_tungsten:0>, null, null, <extrabotany:material:7>, null, null, null, null],[<avaritia:block_resource:2>, <avaritia:resource:5>, null, null, <extrabotany:material:7>, null, null, null, null],[<avaritia:resource:6>, <contenttweaker:block_chaos_tungsten:0>, null, null, <extrabotany:material:7>, null, null, null, null],[null, <avaritia:resource:6>, <contenttweaker:block_chaos_tungsten:0>, null, <extrabotany:material:7>, null, null, null, null],[null, null, <avaritia:resource:6>, <contenttweaker:block_chaos_tungsten:0>, <extrabotany:material:7>, null, null, null, null],[null, null, null, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, null, null, null]]);

// World Breaker
mods.avaritia.ExtremeCrafting.remove(<avaritia:infinity_pickaxe>.withTag({ench: [{lvl: 10 as short, id: 35 as short}]}));
mods.avaritia.ExtremeCrafting.addShaped("WorldBreaker", <avaritia:infinity_pickaxe> * 1, [[null, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, null, null, null], [<avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <contenttweaker:block_chaos_tungsten:0>, null],[null, null, null, null, null, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, null],[null, null, null, null, <avaritia:resource:4>, <contenttweaker:block_chaos_tungsten:0>, <avaritia:resource:6>, <avaritia:resource:6>, null],[null, null, null, <avaritia:resource:4>, <contenttweaker:block_chaos_tungsten:0>, <avaritia:resource:4>, null, <avaritia:resource:6>, <avaritia:resource:6>],[null, null, <avaritia:resource:4>, <contenttweaker:block_chaos_tungsten:0>, <avaritia:resource:4>, null, null, <avaritia:resource:6>, <avaritia:resource:6>],[null, <avaritia:resource:4>, <contenttweaker:block_chaos_tungsten:0>, <avaritia:resource:4>, null, null, null, <avaritia:resource:6>, <avaritia:resource:6>],[<avaritia:resource:4>, <contenttweaker:block_chaos_tungsten:0>, <avaritia:resource:4>, null, null, null, null, <avaritia:resource:6>, <avaritia:resource:6>],[<contenttweaker:block_chaos_tungsten:0>, <avaritia:resource:4>, null, null, null, null, null, <avaritia:resource:6>, null]]);

// Planet Eater
mods.avaritia.ExtremeCrafting.remove(<avaritia:infinity_shovel>);
mods.avaritia.ExtremeCrafting.addShaped("Eater", <avaritia:infinity_shovel> * 1, [[null, null, null, null, null, null, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>], [null, null, null, null, null, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>],[null, null, null, null, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>],[null, null, null, null, <avaritia:resource:4>, <contenttweaker:block_chaos_tungsten:0>, <avaritia:resource:6>, <avaritia:resource:6>, null],[null, null, null, <avaritia:resource:4>, <contenttweaker:block_chaos_tungsten:0>, <avaritia:resource:4>, <avaritia:resource:6>, null, null],[null, null, <avaritia:resource:4>, <contenttweaker:block_chaos_tungsten:0>, <avaritia:resource:4>, null, null, null, null],[null, <avaritia:resource:4>, <contenttweaker:block_chaos_tungsten:0>, <avaritia:resource:4>, null, null, null, null, null],[<avaritia:resource:4>, <contenttweaker:block_chaos_tungsten:0>, <avaritia:resource:4>, null, null, null, null, null, null],[<contenttweaker:block_chaos_tungsten:0>, <avaritia:resource:4>, null, null, null, null, null, null, null]]);

// Nature's Ruin
mods.avaritia.ExtremeCrafting.remove(<avaritia:infinity_axe>);
mods.avaritia.ExtremeCrafting.addShaped("Ruins", <avaritia:infinity_axe> * 1, [[null, null, null, <avaritia:resource:6>, <avaritia:resource:6>, null, null, null, null], [null, null, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, null, null],[null, null, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, null],[null, null, null, <avaritia:resource:6>, <avaritia:resource:4>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>],[null, null, null, <avaritia:resource:4>, <contenttweaker:block_chaos_tungsten:0>, <avaritia:resource:4>, <avaritia:resource:6>, <avaritia:resource:6>, null],[null, null, <avaritia:resource:4>, <contenttweaker:block_chaos_tungsten:0>, <avaritia:resource:4>, null, null, null, null],[null, <avaritia:resource:4>, <contenttweaker:block_chaos_tungsten:0>, <avaritia:resource:4>, null, null, null, null, null],[<avaritia:resource:4>, <contenttweaker:block_chaos_tungsten:0>, <avaritia:resource:4>, null, null, null, null, null, null],[<contenttweaker:block_chaos_tungsten:0>, <avaritia:resource:4>, null, null, null, null, null, null, null]]);

// Hoe of the Green Earth
mods.avaritia.ExtremeCrafting.remove(<avaritia:infinity_hoe>);
mods.avaritia.ExtremeCrafting.addShaped("GreenEarth", <avaritia:infinity_hoe> * 1, [[null, null, null, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, null, null, null], [null, null, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, null, null],[null, null, null, null, <avaritia:resource:6>, <avaritia:resource:4>, <avaritia:resource:6>, <avaritia:resource:6>, null],[null, null, null, null, <avaritia:resource:4>, <contenttweaker:block_chaos_tungsten:0>, <avaritia:resource:4>, <avaritia:resource:6>, <avaritia:resource:6>],[null, null, null, <avaritia:resource:4>, <contenttweaker:block_chaos_tungsten:0>, <avaritia:resource:4>, null, <avaritia:resource:6>, null],[null, null, <avaritia:resource:4>, <contenttweaker:block_chaos_tungsten:0>, <avaritia:resource:4>, null, null, null, null],[null, <avaritia:resource:4>, <contenttweaker:block_chaos_tungsten:0>, <avaritia:resource:4>, null, null, null, null, null],[<avaritia:resource:4>, <contenttweaker:block_chaos_tungsten:0>, <avaritia:resource:4>, null, null, null, null, null, null],[<contenttweaker:block_chaos_tungsten:0>, <avaritia:resource:4>, null, null, null, null, null, null, null]]);

// Infinity Helmet
mods.avaritia.ExtremeCrafting.remove(<avaritia:infinity_helmet>);
mods.avaritia.ExtremeCrafting.addShaped("InfHelm", <avaritia:infinity_helmet> * 1, [[null, null, <avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:4>, null, null], [null, <avaritia:resource:4>, <contenttweaker:block_chaos_tungsten:0>, <contenttweaker:block_chaos_tungsten:0>, <contenttweaker:block_chaos_tungsten:0>, <contenttweaker:block_chaos_tungsten:0>, <contenttweaker:block_chaos_tungsten:0>, <avaritia:resource:4>, null],[<avaritia:resource:4>, <contenttweaker:block_chaos_tungsten:0>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <contenttweaker:block_chaos_tungsten:0>, <avaritia:resource:4>],[<avaritia:resource:4>, <contenttweaker:block_chaos_tungsten:0>, null, <avaritia:resource:5>, <avaritia:resource:6>, <avaritia:resource:5>, null, <contenttweaker:block_chaos_tungsten:0>, <avaritia:resource:4>],[<avaritia:resource:4>, <contenttweaker:block_chaos_tungsten:0>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <contenttweaker:block_chaos_tungsten:0>, <avaritia:resource:4>],[<avaritia:resource:4>, <contenttweaker:block_chaos_tungsten:0>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <contenttweaker:block_chaos_tungsten:0>, <avaritia:resource:4>],[<avaritia:resource:4>, <contenttweaker:block_chaos_tungsten:0>, <avaritia:resource:6>, null, <avaritia:resource:6>, null, <avaritia:resource:6>, <contenttweaker:block_chaos_tungsten:0>, <avaritia:resource:4>],[null, <avaritia:resource:4>, null, null, null, null, null, <avaritia:resource:4>, null],[null, null, null, null, null, null, null, null, null]]);

// Infinity Breastplate
mods.avaritia.ExtremeCrafting.remove(<avaritia:infinity_chestplate>);
mods.avaritia.ExtremeCrafting.addShaped("InfBreast", <avaritia:infinity_chestplate> * 1, [[null, <avaritia:resource:4>, <avaritia:resource:4>, null, null, null, <avaritia:resource:4>, <avaritia:resource:4>, null], [<avaritia:resource:4>, <avaritia:resource:4>, <contenttweaker:block_chaos_tungsten:0>, null, null, null, <contenttweaker:block_chaos_tungsten:0>, <avaritia:resource:4>, <avaritia:resource:4>],[<avaritia:resource:4>, <contenttweaker:block_chaos_tungsten:0>, <contenttweaker:block_chaos_tungsten:0>, null, null, null, <contenttweaker:block_chaos_tungsten:0>, <contenttweaker:block_chaos_tungsten:0>, <avaritia:resource:4>],[null, <avaritia:resource:4>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:4>, null],[null, <avaritia:resource:4>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:block_resource:2>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:4>, null],[null, <avaritia:resource:4>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:4>, null],[null, <avaritia:resource:4>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:4>, null],[null, <avaritia:resource:4>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:4>, null],[null, null, <avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:4>, null, null]]);

// Infinity Leggings
mods.avaritia.ExtremeCrafting.remove(<avaritia:infinity_pants>);
mods.avaritia.ExtremeCrafting.addShaped("InfLeg", <avaritia:infinity_pants> * 1, [[<avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:4>], [<avaritia:resource:4>, <contenttweaker:block_chaos_tungsten:0>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <contenttweaker:block_chaos_tungsten:0>, <avaritia:resource:4>],[<avaritia:resource:4>, <contenttweaker:block_chaos_tungsten:0>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:5>, <avaritia:resource:6>, <avaritia:resource:6>, <contenttweaker:block_chaos_tungsten:0>, <avaritia:resource:4>],[<avaritia:resource:4>, <contenttweaker:block_chaos_tungsten:0>, <avaritia:resource:6>, <avaritia:resource:4>, null, <avaritia:resource:4>, <avaritia:resource:6>, <contenttweaker:block_chaos_tungsten:0>, <avaritia:resource:4>],[<avaritia:resource:4>, <contenttweaker:block_chaos_tungsten:0>, <avaritia:resource:6>, <avaritia:resource:4>, null, <avaritia:resource:4>, <avaritia:resource:6>, <contenttweaker:block_chaos_tungsten:0>, <avaritia:resource:4>],[<avaritia:resource:4>, <avaritia:block_resource:2>, <avaritia:resource:6>, <avaritia:resource:4>, null, <avaritia:resource:4>, <avaritia:resource:6>, <avaritia:block_resource:2>, <avaritia:resource:4>],[<avaritia:resource:4>, <contenttweaker:block_chaos_tungsten:0>, <avaritia:resource:6>, <avaritia:resource:4>, null, <avaritia:resource:4>, <avaritia:resource:6>, <contenttweaker:block_chaos_tungsten:0>, <avaritia:resource:4>],[<avaritia:resource:4>, <contenttweaker:block_chaos_tungsten:0>, <avaritia:resource:6>, <avaritia:resource:4>, null, <avaritia:resource:4>, <avaritia:resource:6>, <contenttweaker:block_chaos_tungsten:0>, <avaritia:resource:4>],[<avaritia:resource:4>, <contenttweaker:block_chaos_tungsten:0>, <avaritia:resource:6>, <avaritia:resource:4>, null, <avaritia:resource:4>, <avaritia:resource:6>, <contenttweaker:block_chaos_tungsten:0>, <avaritia:resource:4>]]);

// Infinity Boots
mods.avaritia.ExtremeCrafting.remove(<avaritia:infinity_boots>);
mods.avaritia.ExtremeCrafting.addShaped("InfBoots", <avaritia:infinity_boots> * 1, [[null, <avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:4>, null, <avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:4>, null], [null, <avaritia:resource:4>, <avaritia:resource:6>, <avaritia:resource:4>, null, <avaritia:resource:4>, <avaritia:resource:6>, <avaritia:resource:4>, null],[null, <avaritia:resource:4>, <avaritia:resource:6>, <avaritia:resource:4>, null, <avaritia:resource:4>, <avaritia:resource:6>, <avaritia:resource:4>, null],[<avaritia:resource:4>, <avaritia:resource:6>, <avaritia:resource:6>, <contenttweaker:block_chaos_tungsten:0>, null, <contenttweaker:block_chaos_tungsten:0>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:4>],[<avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <contenttweaker:block_chaos_tungsten:0>, null, <contenttweaker:block_chaos_tungsten:0>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>],[<contenttweaker:block_chaos_tungsten:0>, <contenttweaker:block_chaos_tungsten:0>, <contenttweaker:block_chaos_tungsten:0>, <nuclearcraft:block_ice>, null, <nuclearcraft:block_ice>, <contenttweaker:block_chaos_tungsten:0>, <contenttweaker:block_chaos_tungsten:0>, <contenttweaker:block_chaos_tungsten:0>],[<nuclearcraft:block_ice>, <nuclearcraft:block_ice>, <nuclearcraft:block_ice>, null, null, null, <nuclearcraft:block_ice>, <nuclearcraft:block_ice>, <nuclearcraft:block_ice>],[null, null, null, null, null, null, null, null, null],[null, null, null, null, null, null, null, null, null]]);

// Cosmic Meatballs
mods.avaritia.ExtremeCrafting.remove(<avaritia:cosmic_meatballs>);
mods.avaritia.ExtremeCrafting.addShaped("CosmicMeatballs", <avaritia:cosmic_meatballs> * 16, [[null, null, null, null, null, null, null, null, null], [null, null, null, null, null, null, null, null, null],[null, null, null, null, <avaritia:resource:4>, null, null, null, null],[null, null, null, <minecraft:porkchop>, <minecraft:beef>, <minecraft:chicken>, null, null, null],[null, null, null, <minecraft:rabbit>, <minecraft:mutton>, <minecraft:fish:0>, null, null, null],[null, null, <iceandfire:fire_dragon_flesh>, <minecraft:fish:1>, <minecraft:fish:2>, <minecraft:rotten_flesh>, <iceandfire:ice_dragon_flesh>, null, null],[null, null, <avaritia:resource:4>, <iceandfire:fire_dragon_heart>, <draconicevolution:dragon_heart>, <iceandfire:ice_dragon_heart>, <avaritia:resource:4>, null, null],[null, null, null, null, null, null, null, null, null],[null, null, null, null, null, null, null, null, null]]);
