# Connector
recipes.remove(<environmentaltech:connector>);
recipes.addShaped(<environmentaltech:connector> * 2, [[<thermalfoundation:storage:1>, <redstonearsenal:material:32>, <thermalfoundation:storage:1>], [<redstonearsenal:material:32>, <draconicevolution:draconic_core>, <redstonearsenal:material:32>],[<thermalfoundation:storage:1>, <redstonearsenal:material:32>, <thermalfoundation:storage:1>]]);
recipes.addShaped(<environmentaltech:connector> * 16, [[<contenttweaker:tungsten_ingot>, <redstonearsenal:material:32>, <contenttweaker:tungsten_ingot>], [<redstonearsenal:material:32>, <draconicevolution:draconic_core>, <redstonearsenal:material:32>],[<contenttweaker:tungsten_ingot>, <redstonearsenal:material:32>, <contenttweaker:tungsten_ingot>]]);

# Litherite Crystal
recipes.remove(<environmentaltech:litherite_crystal>);
recipes.addShaped(<environmentaltech:litherite_crystal> * 4, [[<nuclearcraft:uranium:8>, <actuallyadditions:item_crystal_empowered:4>, <nuclearcraft:thorium:0>], [<actuallyadditions:item_crystal_empowered:4>, <minecraft:diamond_block>, <actuallyadditions:item_crystal_empowered:4>],[<nuclearcraft:thorium:0>, <actuallyadditions:item_crystal_empowered:4>, <nuclearcraft:uranium:8>]]);

# Void Ore Miner Tier 5
recipes.remove(<environmentaltech:void_ore_miner_cont_5>);
mods.avaritia.ExtremeCrafting.addShaped("VOM Tier 5", <environmentaltech:void_ore_miner_cont_5> * 1, [[<environmentaltech:ionite>, <environmentaltech:ionite>, <environmentaltech:ionite>, <environmentaltech:ionite>, <environmentaltech:ionite>, <environmentaltech:ionite>, <environmentaltech:ionite>, <environmentaltech:ionite>, <environmentaltech:ionite>], [<environmentaltech:ionite>, <industrialforegoing:laser_base>, <draconicevolution:draconium_block:1>, <industrialforegoing:laser_base>, <draconicevolution:draconium_block:1>, <industrialforegoing:laser_base>, <draconicevolution:draconium_block:1>, <industrialforegoing:laser_base>, <environmentaltech:ionite>],[<environmentaltech:ionite>, <draconicevolution:draconium_block:1>, <industrialforegoing:laser_lens:0>, <industrialforegoing:laser_lens:15>, <industrialforegoing:laser_lens:14>, <industrialforegoing:laser_lens:13>, <industrialforegoing:laser_lens:12>, <draconicevolution:draconium_block:1>, <environmentaltech:ionite>],[<environmentaltech:ionite>, <industrialforegoing:laser_base>, <industrialforegoing:laser_lens:1>, <draconicevolution:wyvern_energy_core>, <enderio:block_alloy_endergy:4>, <draconicevolution:wyvern_energy_core>, <industrialforegoing:laser_lens:11>, <industrialforegoing:laser_base>, <environmentaltech:ionite>],[<environmentaltech:ionite>, <draconicevolution:draconium_block:1>, <industrialforegoing:laser_lens:2>, <industrialforegoing:laser_drill>, <environmentaltech:void_ore_miner_cont_4>, <industrialforegoing:laser_drill>, <industrialforegoing:laser_lens:10>, <draconicevolution:draconium_block:1>, <environmentaltech:ionite>],[<environmentaltech:ionite>, <industrialforegoing:laser_base>, <industrialforegoing:laser_lens:3>, <draconicevolution:wyvern_energy_core>, <enderio:block_alloy_endergy:4>, <draconicevolution:wyvern_energy_core>, <industrialforegoing:laser_lens:9>, <industrialforegoing:laser_base>, <environmentaltech:ionite>],[<environmentaltech:ionite>, <draconicevolution:draconium_block:1>, <industrialforegoing:laser_lens:4>, <industrialforegoing:laser_lens:5>, <industrialforegoing:laser_lens:6>, <industrialforegoing:laser_lens:7>, <industrialforegoing:laser_lens:8>, <draconicevolution:draconium_block:1>, <environmentaltech:ionite>],[<environmentaltech:ionite>, <industrialforegoing:laser_base>, <draconicevolution:draconium_block:1>, <industrialforegoing:laser_base>, <draconicevolution:draconium_block:1>, <industrialforegoing:laser_base>, <draconicevolution:draconium_block:1>, <industrialforegoing:laser_base>, <environmentaltech:ionite>],[<environmentaltech:interconnect>, <environmentaltech:interconnect>, <environmentaltech:interconnect>, <environmentaltech:interconnect>, <environmentaltech:interconnect>, <environmentaltech:interconnect>, <environmentaltech:interconnect>, <environmentaltech:interconnect>, <environmentaltech:interconnect>]]);

# Void Ore Miner Tier 6
recipes.remove(<environmentaltech:void_ore_miner_cont_6>);
mods.avaritia.ExtremeCrafting.addShaped("Void Ore Miner - TierVI", <environmentaltech:void_ore_miner_cont_6> * 1, [[<draconicevolution:awakened_core>, <environmentaltech:aethium:*>, <environmentaltech:aethium:*>, <actuallyadditions:block_crystal_empowered:2>, <actuallyadditions:block_crystal_empowered:2>, <actuallyadditions:block_crystal_empowered:2>, <environmentaltech:aethium:*>, <environmentaltech:aethium:*>, <draconicevolution:awakened_core>], [<environmentaltech:aethium:*>, <avaritia:neutron_collector>, <avaritia:neutron_collector>, <environmentaltech:aethium:*>, <environmentaltech:aethium:*>, <environmentaltech:aethium:*>, <avaritia:neutron_collector>, <avaritia:neutron_collector>, <environmentaltech:aethium:*>],[<environmentaltech:aethium:*>, <avaritia:neutron_collector>, <contenttweaker:block_blessed_tungsten:0>, <avaritia:neutron_collector>, <draconicevolution:draconic_energy_core>, <avaritia:neutron_collector>, <contenttweaker:block_living_tungsten:0>, <avaritia:neutron_collector>, <environmentaltech:aethium:*>],[<actuallyadditions:block_crystal_empowered:2>, <environmentaltech:aethium:*>, <avaritia:neutron_collector>, <avaritia:resource:4>, <avaritia:neutron_collector>, <avaritia:resource:4>, <avaritia:neutron_collector>, <environmentaltech:aethium:*>, <actuallyadditions:block_crystal_empowered:2>],[<actuallyadditions:block_crystal_empowered:2>, <environmentaltech:aethium:*>, <draconicevolution:draconic_energy_core>, <avaritia:neutron_collector>, <environmentaltech:void_ore_miner_cont_5>, <avaritia:neutron_collector>, <draconicevolution:draconic_energy_core>, <environmentaltech:aethium:*>, <actuallyadditions:block_crystal_empowered:2>],[<actuallyadditions:block_crystal_empowered:2>, <environmentaltech:aethium:*>, <avaritia:neutron_collector>, <avaritia:resource:4>, <avaritia:neutron_collector>, <avaritia:resource:4>, <avaritia:neutron_collector>, <environmentaltech:aethium:*>, <actuallyadditions:block_crystal_empowered:2>],[<environmentaltech:aethium:*>, <avaritia:neutron_collector>, <contenttweaker:block_energized_tungsten:0>, <avaritia:neutron_collector>, <draconicevolution:draconic_energy_core>, <avaritia:neutron_collector>, <contenttweaker:block_nebula_tungsten:0>, <avaritia:neutron_collector>, <environmentaltech:aethium:*>],[<environmentaltech:aethium:*>, <avaritia:neutron_collector>, <avaritia:neutron_collector>, <environmentaltech:aethium:*>, <environmentaltech:aethium:*>, <environmentaltech:aethium:*>, <avaritia:neutron_collector>, <avaritia:neutron_collector>, <environmentaltech:aethium:*>],[<draconicevolution:awakened_core>, <environmentaltech:aethium:*>, <environmentaltech:aethium:*>, <actuallyadditions:block_crystal_empowered:2>, <actuallyadditions:block_crystal_empowered:2>, <actuallyadditions:block_crystal_empowered:2>, <environmentaltech:aethium:*>, <environmentaltech:aethium:*>, <draconicevolution:awakened_core>]]);

# Structure Frame Tier 1
recipes.remove(<environmentaltech:structure_frame_1>);
recipes.addShaped(<environmentaltech:structure_frame_1> * 1, [[<minecraft:iron_ingot>, <actuallyadditions:item_crystal:1>, <minecraft:iron_ingot>], [<environmentaltech:litherite_crystal>, <environmentaltech:interconnect>, <environmentaltech:litherite_crystal>],[<minecraft:iron_ingot>, <actuallyadditions:item_crystal:1>, <minecraft:iron_ingot>]]);

# Structure Frame Tier 2
recipes.remove(<environmentaltech:structure_frame_2>);
recipes.addShaped(<environmentaltech:structure_frame_2> * 1, [[<minecraft:gold_ingot>, <actuallyadditions:item_crystal:1>, <minecraft:gold_ingot>], [<environmentaltech:erodium_crystal>, <environmentaltech:structure_frame_1>, <environmentaltech:erodium_crystal>],[<minecraft:gold_ingot>, <actuallyadditions:item_crystal:1>, <minecraft:gold_ingot>]]);

# Structure Frame Tier 3
recipes.remove(<environmentaltech:structure_frame_3>);
recipes.addShaped(<environmentaltech:structure_frame_3> * 1, [[<minecraft:diamond>, <actuallyadditions:item_misc:5>, <minecraft:diamond>], [<environmentaltech:kyronite_crystal>, <environmentaltech:structure_frame_2>, <environmentaltech:kyronite_crystal>],[<minecraft:diamond>, <actuallyadditions:item_misc:5>, <minecraft:diamond>]]);

# Structure Frame Tier 4
recipes.remove(<environmentaltech:structure_frame_4>);
recipes.addShaped(<environmentaltech:structure_frame_4> * 1, [[<minecraft:emerald>, <actuallyadditions:item_misc:5>, <minecraft:emerald>], [<environmentaltech:pladium_crystal>, <environmentaltech:structure_frame_3>, <environmentaltech:pladium_crystal>],[<minecraft:emerald>, <actuallyadditions:item_misc:5>, <minecraft:emerald>]]);

# Structure Frame Tier 5
recipes.remove(<environmentaltech:structure_frame_5>);
recipes.addShaped(<environmentaltech:structure_frame_5> * 1, [[<avaritia:resource:1>, <minecraft:prismarine_shard>, <avaritia:resource:1>], [<environmentaltech:ionite_crystal>, <environmentaltech:structure_frame_4>, <environmentaltech:ionite_crystal>],[<avaritia:resource:1>, <minecraft:prismarine_shard>, <avaritia:resource:1>]]);

# Structure Frame Tier 6
recipes.remove(<environmentaltech:structure_frame_6>);
recipes.addShaped(<environmentaltech:structure_frame_6> * 1, [[<enderio:item_alloy_endergy_ingot:3>, <draconicevolution:wyvern_core>, <enderio:item_alloy_endergy_ingot:3>], [<environmentaltech:aethium_crystal>, <environmentaltech:structure_frame_5>, <environmentaltech:aethium_crystal>],[<enderio:item_alloy_endergy_ingot:3>, <draconicevolution:wyvern_core>, <enderio:item_alloy_endergy_ingot:3>]]);
